bundling mozilla root CA store for when there are no default certs
crashappsec/nimutils pull request #45
Opened 2024-02-08 22:13 UTC by miki725

not all machines have system certs such as in busybox containers and so by bundling certs from Mozilla we can fallback to them when system certs are missing

2024-02-09 10:39 UTC, ee7 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
```suggestion
  "curl -sSf --retry 5 https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
```

Maybe add some flags like these?

From `curl --help all`:

```text
 -f, --fail        Fail fast with no output on HTTP errors
 -S, --show-error  Show error even when -s is used
 -s, --silent      Silent mode
     --retry <num> Retry request if transient problems occur
```

2024-02-09 10:39 UTC, ee7 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
Do we know how often the certs at this URL are updated? What do we think about committing the output in this repo and `staticRead`ing it?

Arguments in favor:

- Changes would be explicit
- It'd be more robust to upstream weirdness or transient network issues
- It'd avoid a `staticExec` and a network request at compile time
- It's small: about ~18 KiB~ 218 KiB
- It'd maybe be easier to reduce the number of certs later?

Arguments against:

- The certs are no longer auto-updating

Possible middle path: add the certs in this repo, and complain at compile time if the in-repo ones don't match the upstream.

Edit: there's some information on https://wiki.mozilla.org/CA/Maintenance_and_Enforcement

2024-02-09 13:03 UTC, ee7 requested changes

2024-02-09 13:03 UTC, ee7 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
[`staticExec`](https://nim-lang.org/docs/system.html#staticExec%2Cstring%2Cstring%2Cstring) doesn't check the exit code. If we stick with `curl`ing at compile time, we should use [`gorgeEx`](https://nim-lang.org/docs/system.html#gorgeEx%2Cstring%2Cstring%2Cstring) (or a wrapper around that).

For example, this nim program exits successfully:

```nim
const output = staticExec("mycommandthatdoesnotexist")
echo output
```

and prints

```text
/bin/sh: line 1: mycommandthatdoesnotexist: command not found
```

even though the command itself indicates an error.

There are a bunch of other `staticExec`s like this to clean up. But they're on my list.

Edit: I've created https://github.com/crashappsec/chalk/issues/201. I noticed that issue when looking into packaging chalk for Linux package managers (starting with Arch).

2024-02-09 13:46 UTC, miki725 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
good question. yeah not sure what @viega would prefer. dont think certs are updated very often but they do update once-in-a-while so would be nice to get auto-updating behavior. unless we will want to filter out to a subset of CAs though, then vendoring will def be simpler.

@viega what do you think we should do

2024-02-09 16:05 UTC, miki725 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
spoke with @MyNameIsMeerkat and for simplicity we are bundling the full file in the repo for now vs using curl. we can of course change if others have other opinions

2024-02-09 16:06 UTC, miki725 commented on nimutils/net.nim
> +  "curl -s https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites",
good to know. thanks. we changed to use a file so error handling wont be necessary anymore

2024-02-09 16:56 UTC, ee7 reviewed
Bundling the certs sounds good to me, and I've double checked that the ones in this PR are identical to the ones at https://ccadb.my.salesforce-sites.com/mozilla/IncludedRootsPEMTxt?TrustBitsInclude=Websites (modulo whitespace changes).

Note that the certs are 218 KiB, not 18 KiB like I wrote before - I must have either misread/mistyped it. That's still fine by me. But after we merge this PR, we could consider opening a ticket to track the idea to reduce them.

Apologies: I've run out of time right now to review the other changes closely enough for me to approve.

2024-02-09 16:56 UTC, ee7 commented on nimutils/net.nim
> +  stream.write(CA_STORE)
```suggestion
var tmpCAStore = ""

proc getCAStorePath(): string =
  const contents = staticRead(currentSourcePath().parentDir().parentDir() / "files" / "mozilla-root-cas.pem")
  if tmpCAStore != "":
    return tmpCAStore
  let (stream, tmp) = getNewTempFile("cabundle", ".pem")
  stream.write(contents)
```

Nit: prefer to move a `const` to the most restrictive scope, to make it obvious that it's not used elsewhere.

Nit: this also suggests renaming `CA_STORE` to `contents`. I don't mind what the name is, except that a Nim `const` [should only be ALL_CAPS when it's coming from a C wrapper](https://nim-lang.github.io/Nim/nep1.html#style-guidelines-naming-conventions) - I'm also fine with e.g. `CaStore` or `caStore` here.

2024-02-09 17:00 UTC, miki725 commented on nimutils/net.nim
> +  stream.write(CA_STORE)
adjusted

2024-02-11 01:02 UTC, miki725 commented
@viega updated to `curl` the certs on each compile and then using `openssl` command to validate download is not corrupted/etc and that its a valid PEM file

2024-02-12 14:51 UTC, ee7 commented
I think `curl`ing at build time is slightly better overall, partly because it avoids the certs being outdated when building an old version of chalk.

To answer my own question of "how often are these certs updated?", I had a vague memory of curl having a page for this. From [here](https://curl.se/docs/caextract.html):

> This bundle was generated at **Tue Dec 12 04:12:04 2023 GMT**.
>
> This PEM file contains the datestamp of the conversion and we only make a new conversion if there's a change in either the script or the source file. This service checks for updates every day.
>
> ### CA file revisions per date of appearance
> 
> | Date       | Certificates |
> | ---------- | ------------ |
> | 2023-12-12 |          145 |
> | 2023-08-22 |          141 |
> | 2023-05-30 |          137 |
> | 2023-01-10 |          137 |
> | 2022-10-11 |          142 |
> | 2022-07-19 |          140 |
> | 2022-04-26 |          135 |
> | 2022-03-29 |          132 |
> | 2022-03-18 |          132 |
> | 2022-02-01 |          133 |

With this PR, building nimutils the output is:

```text
Embedding Mozilla Root CA store with certificates total found: 147
For more information see https://wiki.mozilla.org/CA/Included_Certificates
```

I'm not sure why there's 2 more, unless the certs were updated today.

But maybe the curl URL is a slightly preferable upstream? Minor advantages:

- it publishes a checksum
- it publishes an update log
- it has a comment for each cert, like everyone's favorite:

```text
Hongkong Post Root CA 3
=======================
-----BEGIN CERTIFICATE-----
MIIFzzCCA7egAwIBAgIUCBZfikyl7ADJk0DfxMauI7gcWqQwDQYJKoZIhvcNAQELBQAwbzELMAkG
A1UEBhMCSEsxEjAQBgNVBAgTCUhvbmcgS29uZzESMBAGA1UEBxMJSG9uZyBLb25nMRYwFAYDVQQK
Ew1Ib25na29uZyBQb3N0MSAwHgYDVQQDExdIb25na29uZyBQb3N0IFJvb3QgQ0EgMzAeFw0xNzA2
MDMwMjI5NDZaFw00MjA2MDMwMjI5NDZaMG8xCzAJBgNVBAYTAkhLMRIwEAYDVQQIEwlIb25nIEtv
bmcxEjAQBgNVBAcTCUhvbmcgS29uZzEWMBQGA1UEChMNSG9uZ2tvbmcgUG9zdDEgMB4GA1UEAxMX
SG9uZ2tvbmcgUG9zdCBSb290IENBIDMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCz
iNfqzg8gTr7m1gNt7ln8wlffKWihgw4+aMdoWJwcYEuJQwy51BWy7sFOdem1p+/l6TWZ5Mwc50tf
jTMwIDNT2aa71T4Tjukfh0mtUC1Qyhi+AViiE3CWu4mIVoBc+L0sPOFMV4i707mV78vH9toxdCim
5lSJ9UExyuUmGs2C4HDaOym71QP1mbpV9WTRYA6ziUm4ii8F0oRFKHyPaFASePwLtVPLwpgchKOe
sL4jpNrcyCse2m5FHomY2vkALgbpDDtw1VAliJnLzXNg99X/NWfFobxeq81KuEXryGgeDQ0URhLj
0mRiikKYvLTGCAj4/ahMZJx2Ab0vqWwzD9g/KLg8aQFChn5pwckGyuV6RmXpwtZQQS4/t+TtbNe/
JgERohYpSms0BpDsE9K2+2p20jzt8NYt3eEV7KObLyzJPivkaTv/ciWxNoZbx39ri1UbSsUgYT2u
y1DhCDq+sI9jQVMwCFk8mB13umOResoQUGC/8Ne8lYePl8X+l2oBlKN8W4UdKjk60FSh0Tlxnf0h
+bV78OLgAo9uliQlLKAeLKjEiafv7ZkGL7YKTE/bosw3Gq9HhS2KX8Q0NEwA/RiTZxPRN+ZItIsG
xVd7GYYKecsAyVKvQv83j+GjHno9UKtjBucVtT+2RTeUN7F+8kjDf8V1/peNRY8apxpyKBpADwID
AQABo2MwYTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAfBgNVHSMEGDAWgBQXnc0e
i9Y5K3DTXNSguB+wAPzFYTAdBgNVHQ4EFgQUF53NHovWOStw01zUoLgfsAD8xWEwDQYJKoZIhvcN
AQELBQADggIBAFbVe27mIgHSQpsY1Q7XZiNc4/6gx5LS6ZStS6LG7BJ8dNVI0lkUmcDrudHr9Egw
W62nV3OZqdPlt9EuWSRY3GguLmLYauRwCy0gUCCkMpXRAJi70/33MvJJrsZ64Ee+bs7Lo3I6LWld
y8joRTnU+kLBEUx3XZL7av9YROXrgZ6voJmtvqkBZss4HTzfQx/0TW60uhdG/H39h4F5ag0zD/ov
+BS5gLNdTaqX4fnkGMX41TiMJjz98iji7lpJiCzfeT2OnpA8vUFKOt1b9pq0zj8lMH8yfaIDlNDc
eqFS3m6TjRgm/VWsvY+b0s+v54Ysyx8Jb6NvqYTUc79NoXQbTiNg8swOqn+knEwlqLJmOzj/2ZQw
9nKEvmhVEA/GcywWaZMH/rFF7buiVWqw2rVKAiUnhde3t4ZEFolsgCs+l6mc1X5VTMbeRRAc6uk7
nwNT7u56AQIWeNTowr5GdogTPyK7SBIdUgC0An4hGh6cJfTzPV4e0hz5sy229zdcxsshTrD3mUcY
hcErulWuBurQB7Lcq9CClnXO0lD+mefPL5/ndtFhKvshuzHQqp9HpLIiyhY6UFfEW0NnxWViA0kB
60PZ2Pierc+xYw5F9KBaLJstxabArahH9CdMOA0uG0k7UvToiIMrVCjU8jVStDKDYmlkDJGcn5fq
dBb9HxEGmpv0
-----END CERTIFICATE-----
```

2024-02-12 18:27 UTC, ee7 requested changes
Looks good, except I think we need to invalidate the cache.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +template getRootCAStoreContent(): string =
```suggestion
proc getRootCAStoreContent(): string =
```

This can be a `proc`, right? In general, it's best practice to use `template` only when necessary. I may suggest later that we convert some other `template` to `proc`.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +    (contents, curlExitCode) = gorgeEx(curlCmd, cache="mozilla-root-store")
It's great that we're checking the exit code now.

However, as-is, I believe the cache is never invalidated. From [the doc comment for `staticExec`](https://github.com/nim-lang/Nim/blob/v2.0.0/lib/system/compilation.nim#L195-L202):

>If `cache` is not empty, the results of `staticExec` are cached within the `nimcache` directory. Use `--forceBuild` to get rid of this caching behaviour then.
> `command & input & cache` (the concatenated string) is used to determine whether the entry in the cache is still valid. You can use versioning information for `cache`:
>```nim
>const stateMachine = staticExec("dfaoptimizer", "input", "0.8.0")
>```

So let's append a current date string like yyyy-mm-dd to the cache string?

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +      "Could not downlaod CA root store: " & contents
```suggestion
      "Could not download CA root store: " & contents
```

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +    caWiki  = "https://wiki.mozilla.org/CA/Included_Certificates"
Non-blocking suggestion: consider moving this closer to the usage site, to clarify that it's not needed initially.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +    opensslCmd             = "openssl storeutl -noout -certs /dev/stdin"
To others, the docs for `openssl storeutl`: https://www.openssl.org/docs/man3.2/man1/openssl-storeutl.html

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +    checkLines             = check.splitLines()
Non-blocking comment: this is a relatively costly split, since it allocates a string for each line (3500 ish of them) at compile time - it's calling the `splitLines` proc, not the iterator. 

It probably doesn't have a significant impact on compile times, but it'd be better to get the index of the start of the last line, and slice from there to the end.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +  echo("For more information see " & caWiki)
```suggestion
  echo "Embedding Mozilla Root CA store with certificates " & checkLines[^1].toLower()
  echo "For more information see " & caWiki
```

Nit: prefer command syntax for things like `echo`. That's also the prevailing style in the codebase.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +      return newContext(verifyMode = CVerifyPeer, caFile = getCAStorePath())
Comment to others: `caFile` has [the highest precendence](https://github.com/nim-lang/Nim/blob/v2.0.0/lib/pure/net.nim#L641-L646). The environment variables `SSL_CERT_FILE` and `SSL_CERT_DIR` are only considered (and with lower precedence) when `verifyMode` is `CVerifyPeerUseEnvVars`.

2024-02-12 18:27 UTC, ee7 commented on nimutils/net.nim
> +    uri = url
```suggestion
  let uri = when url is string: parseUri(url) else: url
```

Nit: for readability, prefer `let` to `var`. Though I realise the previous pattern is used elsewhere.

I'm also fine with a multl-line form, e.g.:

```nim
  let uri = when url is string:
    parseUri(url)
  else:
    url

2024-02-12 18:39 UTC, miki725 commented on nimutils/net.nim
> +  echo("For more information see " & caWiki)
thats not the style Ive seen in chalk. `info`/`trace`/etc seem to always have function parens.

on a side I am actually personally not a fan of the command syntax as I think its confusing thats actually calling a function

2024-02-12 19:11 UTC, ee7 commented on nimutils/net.nim
> +  echo("For more information see " & caWiki)
Yeah, it looks like there's a preference for parens with `info` and `trace` in the chalk repo.

But in this repo it looks like there's a strong preference for omitting parens with `echo`:

```console
$ git rev-parse --short HEAD
b4d6e30
$ git grep 'echo ' -- '*.nim' | wc -l
120
$ git grep 'echo(' -- '*.nim' | wc -l
2
```

As another data point, here's the same for https://github.com/nim-lang/Nim:

```console
$ git rev-parse --short HEAD
a8c168c16
$ git grep 'echo ' -- '*.nim' | wc -l
4861
$ git grep 'echo(' -- '*.nim' | wc -l
560
```

> I am actually personally not a fan of the command syntax as I think its confusing thats actually calling a function

I like it for common functions, to reduce the number of parens. But I'm sympathetic to your point, and I think it can take some getting used to.

2024-02-12 19:13 UTC, miki725 commented on nimutils/net.nim
> +  echo("For more information see " & caWiki)
also I got burned by the `print ...` in py2 vs `print(...)` in py3 so I just like explicit `()` now....

2024-02-12 19:43 UTC, miki725 commented on nimutils/net.nim
> +    caWiki  = "https://wiki.mozilla.org/CA/Included_Certificates"
not following. what usage site? marketing site?

2024-02-12 19:45 UTC, miki725 commented on nimutils/net.nim
> +template getRootCAStoreContent(): string =
saw in some other places which needed compile-time const use `template` vs `proc` so used that but yeah looks like `proc` works equially well here. changing

2024-02-12 19:48 UTC, ee7 commented on nimutils/net.nim
> +    caWiki  = "https://wiki.mozilla.org/CA/Included_Certificates"
Sorry - I meant simply "consider moving the `caWiki` definition down, so that it's directly above the line where it's used":

```Nim
echo("For more information see " & caWiki)
```

2024-02-12 19:55 UTC, ee7 commented on nimutils/net.nim
> +    caWiki  = "https://wiki.mozilla.org/CA/Included_Certificates"
"usage site" isn't standard jargon, but I just meant "the place where the variable is used".  Like how [call site](https://en.wikipedia.org/wiki/Call_site) is the location where a function is called.

2024-02-12 20:05 UTC, miki725 commented on nimutils/net.nim
> +    caWiki  = "https://wiki.mozilla.org/CA/Included_Certificates"
oh. gotcha. I actually put it next to the other url on purpose as the other url was retrieved from this link. if there are obscure links in code I generally like code to have a reference where it came from.

will make it obvious by adding a comment

2024-02-12 20:29 UTC, miki725 commented on nimutils/net.nim
> +    (contents, curlExitCode) = gorgeEx(curlCmd, cache="mozilla-root-store")
date seems fair enough. practivelly as releases will be done in CI nothing will be cached but will help to update certs locally day-by-day. updating

2024-02-12 21:14 UTC, ee7 approved these changes
LGTM, although I haven't written a book on OpenSSL :)

I'm happy to defer this question, but did we have any thoughts on using the certs [published by curl](https://curl.se/docs/caextract.html) instead? Aside from the reasons mentioned in https://github.com/crashappsec/nimutils/pull/45#issuecomment-1938825172, the salesforce URL looks weird to me. Perhaps the curl URL is more likely to stay working?

2024-02-12 21:14 UTC, ee7 commented on nimutils/net.nim
> +    raise newException(ValueError, "Cannot find todays date")
```suggestion
```

The implicitly imported `system.nim` [exports a `CompileDate` global](https://github.com/nim-lang/Nim/blob/v2.0.0/lib/system/compilation.nim#L28) - let's just use that instead.

That global is used to set the compile date in the output of `nim --version`.

2024-02-12 21:14 UTC, ee7 commented on nimutils/net.nim
> +    cache   = "mozilla-root-store-" & today # cache certs by day
```suggestion
    cache   = "mozilla-root-store-" & CompileDate # cache certs by day
```

2024-02-12 21:23 UTC, ee7 commented on nimutils/net.nim
> +    (contents, curlExitCode) = gorgeEx(curlCmd, cache="mozilla-root-store")
Historically, some release binaries have been built locally. I'd prefer that not to happen, but this also guards against outdated certs in situations like that.

2024-02-12 22:13 UTC, miki725 commented on nimutils/net.nim
> +    raise newException(ValueError, "Cannot find todays date")
awesome. and I was trying to google for it too. docs discovery is hard sometimes. 😭

2024-02-12 22:24 UTC, miki725 commented
not sure about grabbing it from curls site. thought to get it from the original link in case curl does any massaging but happy to change. cc @MyNameIsMeerkat @viega thoughts?

2024-02-13 13:45 UTC, MyNameIsMeerkat commented
> not sure about grabbing it from curls site. thought to get it from the original link in case curl does any massaging but happy to change. cc @MyNameIsMeerkat @viega thoughts?

I feel like we are splitting hairs at this point, the salesforce/microsoft link _looks_ weird for sure but is one of the official sources cited by CCADB (https://www.ccadb.org/resources) so I have no concerns using it and would tend to have more trust in that as a source than using curl's website tbh.

Let's just get this done and merged

2024-02-14 11:16 UTC, ee7 commented
I did approve, so I'm happy for us to merge this. From my side, I think we can defer any further discussion to a follow-up issue/PR.

2024-02-14 13:51 UTC, merged