passing pty through in runCmdGetEverything
crashappsec/nimutils pull request #46
Opened 2024-02-15 18:06 UTC by miki725

the issue we are trying to solve is:

```
echo foo | bar --stdin
```

If bar is reading its input from stdin, stdin needs to close
so that bar can proceed. If stdin is not closed, bar is hang
waiting for the stdin.

In libc if stdin is closed we get a `read()` output of 0
after a read which returned some data:

```
read("foo\n") -> 4
read("") -> 0 // as stdin closed
```

if the stdin is not closed, the second read will hang forever
as it will wait for the stdin to close

What the fix does here is that when it sees a read() returning 0
it passes that indication to all the subscribers to let them know
that the write FD should be closed to mimick what we got on the input
side of the switchboard.

Also it fixes some mixed whitespace as things werent rendering well
in vim.

2024-02-16 13:08 UTC, ee7 commented
Nice work on fixing this.

But can we please:

- Create a new PR with the whitespace-only changes, and enforce the style in CI
- Merge that PR
- Rebase this PR on top

It's straightforward to review this PR without the whitespace changes (well, at least locally; GitHub hides the option somewhat), but a commit [should be a single logical unit of change](https://www.kernel.org/doc/html/latest/process/submitting-patches.html#split-changes). Somebody who looks at this PR or the merged commit later shouldn't be forced to hide whitespace changes in order to understand the diff.

A PR may be multiple logical units of change, but then it should be multiple commits that are preserved (that is, without squashing) on merging to the main branch.

2024-02-16 16:04 UTC, miki725 commented
as there is no de-facto autoformatter for C I manually mixed some of the mixed whitespace in C files I had to debug to fix this bug. splitting that out will be much more pain than provide benefit. we can add CI validation for that in the future change. there is more mixed whitespace in the repo

2024-02-16 17:05 UTC, viega requested changes
I think the work is solid, just not where I think the API change should be made, per my other comment.

The subscription object should track, and the publish needs to consult that before propagating (whereas the typical message gets broadcast to all subscribers). 

Possibly it's best to have a separate version of publish for when this situation occurs, to keep it down to a single test per message (and that test is both fine where you have it, and was no net additional cost).

I'm 100% fine if you don't want to make that change, but if not, I'd prefer only addressing this for your current use case, and I can come in and make the change later.  Or, you can continue to overachieve, that's fine too :)

2024-02-16 17:05 UTC, viega commented on nimutils/c/switchboard.c
> +    fd_obj->close_fd_when_done   = close_when_done;
As I'm taking a first scan of the code, I'm confused.

Is this flag going to cause the fd actually closing on its own lead to us PROPAGATING the close? Because:
1. If so, the name isn't clear.
2. I don't think this should be done per data source, I think it should be done per SUBSCRIPTION. 

As just a real simple example, if I'm multiplexing a shell, and the user's stdin disappears, we established yesterday that I probably don't want to let the child shell know one of the parents is gone. HOWEVER, if that multiplexing is ALSO capturing an input log with a second subscription, I *do* want to know about that.

2024-02-16 17:05 UTC, viega commented on nimutils/c/switchboard.c
> +    fd_obj->close_fd_when_done   = close_when_done;
I guess I'd call the flag something like `proxy_close` at the subscription level, and `proxy_stdin_close` at the `runCmd` level?

Really that's the issue, controlling whether to propagate closes for subscriptions (proxy is probably both clearer to more people and more concise?)

2024-02-16 17:15 UTC, miki725 commented on nimutils/c/switchboard.c
> +    fd_obj->close_fd_when_done   = close_when_done;
ah right makes sense. Ill adjust. thanks

2024-02-19 16:14 UTC, viega approved these changes
Well done, thanks.

2024-02-19 17:04 UTC, merged